Fix "E501 line too long (155 > 88 characters)"
Flake8 reported the following Errors:

Run flake8
./deepl/__init__.py:3:1: F401 '.api.translate' imported but unused
from .api import translate
^
./deepl/api.py:23:89: E501 line too long (155 > 88 characters)
    "user-agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Mobile Safari/537.36",
                                                                                        ^
./tests/test_sentence_split.py:5:89: E501 line too long (94 > 88 characters)
    text = "This is a text. This text has words. The end? The end! I'm not sure... who knows."
                                                                                        ^
2     E501 line too long (155 > 88 characters)
1     F401 '.api.translate' imported but unused
3
Error: Process completed with exit code 1.